apiVersion: v1
kind: ConfigMap
metadata:
  namespace: k8slive
  name: zerofiltretech-blog-api
data:
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: INFO
  LOGGING_LEVEL_ORG_HIBERNATE_SQL: DEBUG
  LOGGING_LEVEL_TECH_ZEROFILTRE: DEBUG

  SERVER_PORT: "80"

  THROTTLING_CAPACITY: "50"
  THROTTLING_TIME_SECONDS: "1"

  SPRING_LIQUIBASE_CHANGELOG: classpath:/liquibase/db/changelog/db.changelog-dev.yaml

  SPRING_MAIL_HOST: smtp.gmail.com
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_USERNAME: votre_adresse@gmail.com
  SPRING_DATASOURCE_USERNAME: blog_api_dev
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-test.zerofiltre-bootcamp.svc.cluster.local:3306/blogapidb_dev
  HIBERNATE_DDL_AUTO: update
  ZEROFILTRE_ENV: dev

  SECURITY_JWT_EXPIRATION: "86400" #seconds
  SECURITY_VERIFICATION_TOKEN_EXPIRATION: "604800" #7 days
  SECURITY_JWT_URI: /auth/**

  GITHUB_CLIENT_ID: clid
  STACKOVERFLOW_KEY: key
  ALLOWED_ORIGINS_PATTERN: '*'

  REMINDER_RATE: "864000000" #10 days
  REMINDER_INITIAL_DELAY: "864000000" #10 days
  CUSTOMER_PORTAL_LINK: https://billing.stripe.com/p/login/test_28odSt4jj89l8kE6oo
  OVH_USERNAME: user-ovh
  OVH_AUTH_URL: https://auth.cloud.ovh.net/v3/auth/tokens?nocatalog
  VIMEO_ROOT_URL: https://api.vimeo.com
  CHECKOUT_REMINDER_DELAY_MS: "60000" #1min
  CHECKOUT_REMINDER_CHECK_FREQUENCY_MS: "30000" #30s
  ZEROFILTRE_INFRA_STATS_REMINDER_CRON: "0 0 13 1 * ?"
  ZEROFILTRE_INFRA_MOBILE_PAYMENTS_REMINDER_CRON: "0 0 0 * * ?" #every at midnight
  SANDBOX_K8S_DOC: https://github.com/Zerofiltre-Courses/bootcamp-devops-dev/blob/main/k8s/k8s_README.md
  K8S_PROVISIONER_URL: https://provisioner-dev.zerofiltre.tech
  NOTCHPAY_PUBLIC_KEY: pk_test.key

  #Opentelemetry
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otelcol-opentelemetry-collector.zerofiltre-bootcamp.svc.cluster.local:4317
